import { render } from "@testing-library/react";
import ActionsButton from "components/Action";

export const columns = [
  {
    title: "S.NO",
    dataIndex: "serialNumber",
    key: "serialNumber",
    align: "center",
    render: (text, record, index) => {
      return index + 1;
    },
  },

  {
    title: "Voter Id",
    dataIndex: "voterId",
    key: "voterId",
    align: "center",
    sorter: (a, b) => a.voterId.localeCompare(b.voterId),
  },
  {
    title: "Name",
    dataIndex: "name",
    key: "name",
    align: "center",
    sorter: (a, b) => a.name.localeCompare(b.name),
  },
  {
    title: "नाम",
    dataIndex: "hiName",
    key: "hiName",
    align: "center",
    sorter: (a, b) => a.hiName.localeCompare(b.hiName),
  },
  {
    title: "Father Name",
    dataIndex: "fatherName",
    key: "fatherName",
    align: "center",
    sorter: (a, b) => a.fatherName.localeCompare(b.fatherName),
  },
  {
    title: "पिता का नाम",
    dataIndex: "hiFatherName",
    key: "hiFatherName",
    align: "center",
    sorter: (a, b) => a.hiFatherName.localeCompare(b.hiFatherName),
  },
  {
    title: "Gender",
    dataIndex: "gender",
    key: "gender",
    align: "center",
    sorter: (a, b) => a.gender.localeCompare(b.gender),
  },
  {
    title: "Caste Name",
    dataIndex: "caste",
    key: "caste",
    align: "center",
    sorter: (a, b) => a.caste.localeCompare(b.caste),
  },
  {
    title: "जाति",
    dataIndex: "hiCasteName",
    key: "hiCasteName",
    align: "center",
    sorter: (a, b) => a.hiCasteName.localeCompare(b.hiCasteName),
  },
  {
    title: "Religion Name",
    dataIndex: "caste",
    key: "caste",
    align: "center",
    sorter: (a, b) => a.caste.localeCompare(b.caste),
  },
  {
    title: "धर्म",
    dataIndex: "hiReligionName",
    key: "hiReligionName",
    align: "center",
    sorter: (a, b) => a.hiReligionName.localeCompare(b.hiReligionName),
  },
  {
    title: "Nigam ward",
    dataIndex: "section",
    key: "section",
    align: "center",
    sorter: (a, b) => a.section.localeCompare(b.section),
  },
  {
    title: "निगम वार्ड",
    dataIndex: "hisection",
    key: "hisection",
    align: "center",
    sorter: (a, b) => a.section.localeCompare(b.section),
  },
  {
    title: "Booth",
    dataIndex: "booth",
    key: "booth",
    align: "center",
    sorter: (a, b) => a.booth.localeCompare(b.booth),
  },
  {
    title: "मतदान केंद्र",
    dataIndex: "hibooth",
    key: "hibooth",
    align: "center",
    sorter: (a, b) => a.hibooth.localeCompare(b.hibooth),
  },

  {
    title: "House No",
    dataIndex: "houseNo",
    key: "houseNo",
    align: "center",
    sorter: (a, b) => parseInt(a.houseNo) - parseInt(b.houseNo),
  },
  {
    title: "City",
    dataIndex: "city",
    key: "city",
    align: "center",
    sorter: (a, b) => a.city.localeCompare(b.city),
  },
  {
    title: "Vidhansabha",
    dataIndex: "vidhansabha",
    key: "vidhansabha",
    align: "center",
    sorter: (a, b) => a.vidhansabha.localeCompare(b.vidhansabha),
  },
  {
    title: "LokSabha",
    dataIndex: "loksabha",
    key: "loksabha",
    align: "center",
    sorter: (a, b) => a.loksabha.localeCompare(b.loksabha),
  },
  {
    title: "Mobile Number",
    dataIndex: "mobileNumber",
    key: "mobileNumber",
    align: "center",
    sorter: (a, b) => a.mobileNumber.localeCompare(b.mobileNumber),
  },
  {
    title: "District",
    dataIndex: "district",
    key: "district",
    align: "center",
    sorter: (a, b) => a.district.localeCompare(b.district),
  },
  {
    title: "Address",
    dataIndex: "newAddress",
    key: "newAddress",
    align: "center",
    sorter: (a, b) => a.newAddress.localeCompare(b.newAddress),
  },
  {
    title: "पता",
    dataIndex: "hiNewAddress",
    key: "hiNewAddress",
    align: "center",
    sorter: (a, b) => a.hiNewAddress.localeCompare(b.hiNewAddress),
  },
  {
    title: "Create Date",
    dataIndex: "createdAt",
    key: "createdAt",
    align: "center",
    sorter: (a, b) => a.createdAt.localeCompare(b.createdAt),
  },
  {
    title: "Update Date",
    dataIndex: "updatedAt",
    key: "updatedAt",
    align: "center",
    sorter: (a, b) => a.updatedAt.localeCompare(b.updatedAt),
  },
  {
    title: "Action",
    dataIndex: "action",
    key: "acion",
    align: "center",
    render: (text, record) => <ActionsButton record={record} text={text} />,
  },
];

export const data = [
  {
    key: "1",
    name: "Alice",
    voterId: "6129n",
    fatherName: "Brown",
    gender: "Male",
    boothPart: "indore124",
    houseNo: "10",
    city: "Bhopal",
    vidhansabha: "indore-7",
    lookSabha: "Indore-4",
    district: "Indore",
    mobileNumber: "9036837628",
    village: "Village2",
  },
  {
    key: "2",
    name: "Sophia",
    voterId: "3967s",
    fatherName: "Lee",
    gender: "Female",
    boothPart: "indore122",
    houseNo: "40",
    city: "Ujjain",
    vidhansabha: "indore-5",
    lookSabha: "Indore-2",
    district: "Bhopal",
    mobileNumber: "9031125903",
    village: "Village1",
  },
  {
    key: "3",
    name: "Rupesh",
    voterId: "6129n",
    fatherName: "Brown",
    gender: "Male",
    boothPart: "indore124",
    houseNo: "120",
    city: "Bhopal",
    vidhansabha: "indore-7",
    lookSabha: "Indore-4",
    district: "Indore",
    mobileNumber: "9036837628",
    village: "Village2",
  },
  {
    key: "4",
    name: "Sophia",
    voterId: "3967s",
    fatherName: "Lee",
    gender: "Female",
    boothPart: "indore122",
    houseNo: "150",
    city: "Ujjain",
    vidhansabha: "indore-5",
    lookSabha: "Indore-2",
    district: "Bhopal",
    mobileNumber: "9031125903",
    village: "Village1",
  },
  {
    key: "5",
    name: "Anil",
    voterId: "6129n",
    fatherName: "Brown",
    gender: "Male",
    boothPart: "indore124",
    houseNo: "66",
    city: "Bhopal",
    vidhansabha: "indore-7",
    lookSabha: "Indore-4",
    district: "Indore",
    mobileNumber: "9036837628",
    village: "Village2",
  },
  {
    key: "6",
    name: "Abhay",
    voterId: "3967s",
    fatherName: "Lee",
    gender: "Female",
    boothPart: "indore122",
    houseNo: "55",
    city: "Ujjain",
    vidhansabha: "indore-5",
    lookSabha: "Indore-2",
    district: "Bhopal",
    mobileNumber: "9031125903",
    village: "Village1",
  },
  {
    key: "7",
    name: "Yogesh",
    voterId: "6129n",
    fatherName: "Brown",
    gender: "Male",
    boothPart: "indore124",
    houseNo: "25",
    city: "Bhopal",
    vidhansabha: "indore-7",
    lookSabha: "Indore-4",
    district: "Indore",
    mobileNumber: "9036837628",
    village: "Village2",
  },
  {
    key: "8",
    name: "Kapil",
    voterId: "3967s",
    fatherName: "Lee",
    gender: "Female",
    boothPart: "indore122",
    houseNo: "15",
    city: "Ujjain",
    vidhansabha: "indore-5",
    lookSabha: "Indore-2",
    district: "Bhopal",
    mobileNumber: "9031125903",
    village: "Village1",
  },
  {
    key: "9",
    name: "Hemraj",
    voterId: "6129n",
    fatherName: "Brown",
    gender: "Male",
    boothPart: "indore124",
    houseNo: "20",
    city: "Bhopal",
    vidhansabha: "indore-7",
    lookSabha: "Indore-4",
    district: "Indore",
    mobileNumber: "9036837628",
    village: "Village2",
  },
  {
    key: "10",
    name: "Ankit",
    voterId: "3967s",
    fatherName: "Lee",
    gender: "Female",
    boothPart: "indore122",
    houseNo: "60",
    city: "Ujjain",
    vidhansabha: "indore-5",
    lookSabha: "Indore-2",
    district: "Bhopal",
    mobileNumber: "9031125903",
    village: "Village1",
  },
  {
    key: "11",
    name: "aliya",
    voterId: "6129n",
    fatherName: "Brown",
    gender: "Male",
    boothPart: "indore124",
    houseNo: "10",
    city: "Bhopal",
    vidhansabha: "indore-7",
    lookSabha: "Indore-4",
    district: "Indore",
    mobileNumber: "9036837628",
    village: "Village2",
  },
  {
    key: "12",
    name: "Abhishek",
    voterId: "3967s",
    fatherName: "Lee",
    gender: "Female",
    boothPart: "indore122",
    houseNo: "30",
    city: "Ujjain",
    vidhansabha: "indore-5",
    lookSabha: "Indore-2",
    district: "Bhopal",
    mobileNumber: "9031125903",
    village: "Village1",
  },
  {
    key: "13",
    name: "Arjun",
    voterId: "6129n",
    fatherName: "Brown",
    gender: "Male",
    boothPart: "indore124",
    houseNo: "55",
    city: "Bhopal",
    vidhansabha: "indore-7",
    lookSabha: "Indore-4",
    district: "Indore",
    mobileNumber: "9036837628",
    village: "Village2",
  },
  {
    key: "14",
    name: "VishnuPratap",
    voterId: "3967s",
    fatherName: "Lee",
    gender: "Female",
    boothPart: "indore122",
    houseNo: "1",
    city: "Ujjain",
    vidhansabha: "indore-5",
    lookSabha: "Indore-2",
    district: "Bhopal",
    mobileNumber: "9031125903",
    village: "Village1",
  },
  {
    key: "15",
    name: "Aakksh",
    voterId: "6129n",
    fatherName: "Brown",
    gender: "Male",
    boothPart: "indore124",
    houseNo: "40",
    city: "Bhopal",
    vidhansabha: "indore-7",
    lookSabha: "Indore-4",
    district: "Indore",
    mobileNumber: "9036837628",
    village: "Village2",
  },
  {
    key: "16",
    name: "Devraj",
    voterId: "3967s",
    fatherName: "Lee",
    gender: "Male",
    boothPart: "indore122",
    houseNo: "20",
    city: "Ujjain",
    vidhansabha: "indore-5",
    lookSabha: "Indore-2",
    district: "Bhopal",
    mobileNumber: "9031125903",
    village: "Village1",
  },
  {
    key: "1",
    name: "Nirved",
    voterId: "6129n",
    fatherName: "Brown",
    gender: "Male",
    boothPart: "indore124",
    houseNo: "11",
    city: "Bhopal",
    vidhansabha: "indore-7",
    lookSabha: "Indore-4",
    district: "Indore",
    mobileNumber: "9036837628",
    village: "Village2",
  },
  {
    key: "2",
    name: "Somya",
    voterId: "3967s",
    fatherName: "Lee",
    gender: "Female",
    boothPart: "indore122",
    houseNo: "10",
    city: "Ujjain",
    vidhansabha: "indore-5",
    lookSabha: "Indore-2",
    district: "Bhopal",
    mobileNumber: "9031125903",
    village: "Village1",
  },
];
